name: savant
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  bit_array: ^2.0.0
  equatable: ^1.2.5

dev_dependencies:
  pedantic: ^1.9.0
